### ISSUE TITLE
Update of GSF (33 beta) not possible - different signature

### ISSUE THREAD

**Issue by robovoice1** [GrapheneOS/platform_packages_apps_Updater#64]
![Screenshot_20220905-002529](https://user-images.githubusercontent.com/92784377/188336129-73083cbb-a68e-4bf9-bbd7-3c32e0a97e38.png)
![Screenshot_20220905-002504](https://user-images.githubusercontent.com/92784377/188336143-72a833a0-1cf8-413e-8771-5b82e969aaf5.png)

Pixel 6 pro
TP1A.220624.021.2022083000

**Comment by thestinger** [comment]
Not a bug, the GSF signing key changed at one point and doesn't use a key rotation proof.

**Comment by thestinger** [comment]
GSF is meant to be bundled with the OS and this is a limitation of it being a user installed app. It's not due to any bug or mistake on our part. This is simply the way it is with the current approach. You can defer updating it if you want to wait until a possible smoother upgrade path if we end up implementing some way of doing that.
